### ISSUE TITLE
ssr-subscribe update failed, "Error: socket hang up"

### ISSUE THREAD

**Issue by zhdsmy** [noahziheng/ssr-helper#1]
michael@MichaelZhang-PC:~$ ssr-subscribe update
✖ https://xxxxx.xxxxx
/home/michael/.config/yarn/global/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at TLSSocket.socketOnEnd (_http_client.js:344:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by noahziheng** [comment]
Hello,
Please make sure your SSR Subscribe URL is valid and it must be connectable behind GFW under v1.0.1.
I'll add feature update subscription through proxy when next version.
And you can use some tool like proxychains for ssr-subscibe command.It maybe useful for you.
