### ISSUE TITLE
 libsodium not found

### ISSUE THREAD

**Issue by GreenHatHG** [noahziheng/ssr-helper#10]
Traceback (most recent call last):
  File "/media/cc/下载/linux/解压/shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "/media/cc/下载/linux/解压/shadowsocksr/shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "/media/cc/下载/linux/解压/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 299, in get_config
    check_config(config, is_local)
  File "/media/cc/下载/linux/解压/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/media/cc/下载/linux/解压/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/media/cc/下载/linux/解压/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/media/cc/下载/linux/解压/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/media/cc/下载/linux/解压/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 71, in __init__
    load_libsodium()
  File "/media/cc/下载/linux/解压/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found
Error: Script execute failed!

请问这个是什么回事，我尝试安装了libsodium-1.0.1，但是还是不行，不知道把libsodium-1.0.1放在哪个文件夹，谢谢

**Comment by noahziheng** [comment]
Hello GreenHatHG,
 加密方式为 chacha20 的情况下，SSR Python 会使用 libsodium 依赖，Debian 系(Debian/Ubuntu/Mint/Deepin)下可用 `sudo apt install libsodium`，其他发行版可自行编译安装,文档[在此](https://download.libsodium.org/doc/installation/)。

Thanks for feedback,
Noah

**Comment by GreenHatHG** [comment]
ok,谢谢，我有空试下
