### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by neofung** [noahziheng/ssr-helper#2]
```
/home/neo/.nvm/versions/node/v8.4.0/lib/node_modules/ssr-helper/lib/decode.js:8
  let i = servers.length
                 ^

TypeError: Cannot read property 'length' of undefined
    at main (/home/neo/.nvm/versions/node/v8.4.0/lib/node_modules/ssr-helper/lib/decode.js:8:18)
    at Object.<anonymous> (/home/neo/.nvm/versions/node/v8.4.0/lib/node_modules/ssr-helper/lib/select.js:4:15)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/neo/.nvm/versions/node/v8.4.0/lib/node_modules/ssr-helper/bin/ssr-ls.js:1:63)
```

**Comment by noahziheng** [comment]
Hello,
Can u offer more infomation?What do you did before the error is threw?
你好，
能提供更多的信息供检查吗？比如在报错前你做了啥，在何种环境下运行。

**Comment by neofung** [comment]
ssr 版本 https://github.com/shadowsocksr-backup/shadowsocksr/commit/fd723a92c488d202b407323f0512987346944136 
node版本: v6.11.2
特意新clone一个ssr来测试，没有对其进行任何操作，包括修改配置
npm安装，config了ssr的路径后，执行 ssr ls, 返回如题的错误。执行ssr add并填写所需要内容后，返回 
```bash
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'push' of undefined
```

**Comment by noahziheng** [comment]
目测也是，找找看~/.config/ssr-helper-nodejs/config.json是否存在，存在的话把内容发上来看看

**Comment by neofung** [comment]
{
	"ssr-path": "/home/neo/src/neofung/shadowsocksr/",
	"servers": []
}

**Comment by neofung** [comment]
看了一眼config.json的权限。。。
```
-rw-rw-r--  1 neo neo   70 9月  11 15:06 config.json
```
其他用户不可写，chmod 666 后没问题了

**Comment by noahziheng** [comment]
其他用户？你用了root？正常情况下不会出现这个问题，我的测试机和你的这个文件权限是一样的

**Comment by neofung** [comment]
不是用了root。我的npm是用nvm安装的，不清楚为什么原来config.json 按照原来权限不能写入。

**Comment by noahziheng** [comment]
这就很奇怪了，再观察有没有类似现象发生~感谢反馈
