### ISSUE TITLE
ssr uri 无法添加

### ISSUE THREAD

**Issue by Runninghole** [noahziheng/ssr-helper#4]
如下
zhuwendong@black:~$ ssr add ssr://xxxxx
[1] 9533
[2] 9534
[2]+  已完成               group=Q0NDQVQ
zhuwendong@black:~$ buffer.js:179
    throw new TypeError(kFromErrorMsg);
    ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:179:11)
    at parseCore (/usr/local/lib/node_modules/ssr-helper/lib/parse.js:33:22)
    at main (/usr/local/lib/node_modules/ssr-helper/lib/parse.js:9:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ssr-helper/bin/ssr-add.js:42:25)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Modu^C
[1]+  退出 1                ssr add ssr://xxxxx
zhuwendong@black:~$ ssr ls
Error: You havn't add any host!

**Comment by noahziheng** [comment]
Hello,
信息不太够，从错误来看是SSR URI不符合规范或者复制了多余的字符导致的，可尝试将ssr://后面的部分进行base64解码看看能不能正常解析出来

Noah
