### ISSUE TITLE
let path = program.args[0]

### ISSUE THREAD

**Issue by JimmyChangJY** [noahziheng/ssr-helper#8]
Linux Mint 18.3
rpm insall 
git manyuser okay
then I type below 
get error message 

XXXXX@NAS ~ $ ssr config /home/XXXXX/shadowsocksr
/usr/local/lib/node_modules/ssr-helper/bin/ssr-config.js:7
let path = program.args[0]
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by noahziheng** [comment]
Hello Jimmy,
The current version of SSR Helper is base on Node.js v6+.So you need upgrade the latest Node.js LTS.

Thanks for feedback,
Noah
